default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  reaping_frequency: 10
  timeout: 5000

development:
  <<: *default
  database: instalaunchx_development

test:
  <<: *default
  database: instalaunchx_test

production:
  <<: *default
